version: '3'

services:
  frontend-app:
    image: volunteer-victoria-fe:dev
    container_name: volunteer-victoria-fe
    build:
      context: ./packages/front_end
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./packages/front_end:/usr/src/app/front_end
      - /usr/src/app/front_end/app/node_modules
    # depends_on:
    #   - backend-app
    networks:
      - backend
      
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      - ./packages/api:/usr/src/app/api
      - ./packages/api/node_modules:/usr/src/app/api/node_modules
    depends_on:
      - localstack
    networks:
      - backend
    environment:
      - NODE_ENV=docker
      - AWS_DEFAULT_REGION=ca-central-1
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=yyy
      - DB_ENDPOINT=http://localstack:4566
      - HOST_PORT=4000
  
  localstack:
    image: localstack/localstack:0.12.15
    ports:
      - '127.0.0.1:4510-4559:4510-4559' # external service port range
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:8080:8080'
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - EXTRA_CORS_ALLOWED_ORIGIN=file://
    volumes:
      - './.aws:/docker-entrypoint-initaws.d'
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
