name: Build And Deploy

on:
  push:
    tags:
      - dev

env:
  TF_VERSION: 1.1.8

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Extract tag name
        run: echo "ENV_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Print local env
        run: make print-env

      - uses: actions/cache@v2
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Print local env
        run: make print-env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ca-central-1

      - name: Init Terraform
        run: make init

      - name: Build API
        run: make build-api

      # - name: Build App
      #   run: make build-app

      - name: Deploy infrastructure and API
        run: make deploy-tf

      # - name: Deploy app to CloudFront
      #   run: make deploy-app
